# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_gateway.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'llm_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import chameleon.core.v1.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_gateway.proto\x12\x11\x63hameleon.core.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"\x8e\x01\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x36\n\ncomplexity\x18\x02 \x01(\x0e\x32\".chameleon.core.v1.ModelComplexity\x12\x33\n\x06\x63onfig\x18\x03 \x01(\x0b\x32#.chameleon.core.v1.GenerationConfig\"c\n\x10GenerationConfig\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\x12\x0e\n\x06stream\x18\x03 \x01(\x08\x12\x16\n\x0estop_sequences\x18\x04 \x03(\t\"\xcd\x01\n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nmodel_used\x18\x02 \x01(\t\x12;\n\x0f\x63omplexity_used\x18\x03 \x01(\x0e\x32\".chameleon.core.v1.ModelComplexity\x12\x32\n\x0btoken_usage\x18\x04 \x01(\x0b\x32\x1d.chameleon.core.v1.TokenUsage\x12\x12\n\nlatency_ms\x18\x05 \x01(\x03\x12\x12\n\nfrom_cache\x18\x06 \x01(\x08\"T\n\nTokenUsage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x05\"\x9f\x01\n\x13ModelStatusResponse\x12\x42\n\x06models\x18\x01 \x03(\x0b\x32\x32.chameleon.core.v1.ModelStatusResponse.ModelsEntry\x12\x15\n\rdefault_model\x18\x02 \x01(\t\x1a-\n\x0bModelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*S\n\x0fModelComplexity\x12\x1a\n\x16\x43OMPLEXITY_UNSPECIFIED\x10\x00\x12\x08\n\x04\x46\x41ST\x10\x01\x12\x0c\n\x08\x42\x41LANCED\x10\x02\x12\x0c\n\x08POWERFUL\x10\x03\x32\xdf\x02\n\x11LLMGatewayService\x12S\n\x08Generate\x12\".chameleon.core.v1.GenerateRequest\x1a#.chameleon.core.v1.GenerateResponse\x12[\n\x0eStreamGenerate\x12\".chameleon.core.v1.GenerateRequest\x1a#.chameleon.core.v1.GenerateResponse0\x01\x12P\n\x0eGetModelStatus\x12\x16.google.protobuf.Empty\x1a&.chameleon.core.v1.ModelStatusResponse\x12\x46\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1f.chameleon.core.v1.HealthStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELSTATUSRESPONSE_MODELSENTRY']._loaded_options = None
  _globals['_MODELSTATUSRESPONSE_MODELSENTRY']._serialized_options = b'8\001'
  _globals['_MODELCOMPLEXITY']._serialized_start=785
  _globals['_MODELCOMPLEXITY']._serialized_end=868
  _globals['_GENERATEREQUEST']._serialized_start=84
  _globals['_GENERATEREQUEST']._serialized_end=226
  _globals['_GENERATIONCONFIG']._serialized_start=228
  _globals['_GENERATIONCONFIG']._serialized_end=327
  _globals['_GENERATERESPONSE']._serialized_start=330
  _globals['_GENERATERESPONSE']._serialized_end=535
  _globals['_TOKENUSAGE']._serialized_start=537
  _globals['_TOKENUSAGE']._serialized_end=621
  _globals['_MODELSTATUSRESPONSE']._serialized_start=624
  _globals['_MODELSTATUSRESPONSE']._serialized_end=783
  _globals['_MODELSTATUSRESPONSE_MODELSENTRY']._serialized_start=738
  _globals['_MODELSTATUSRESPONSE_MODELSENTRY']._serialized_end=783
  _globals['_LLMGATEWAYSERVICE']._serialized_start=871
  _globals['_LLMGATEWAYSERVICE']._serialized_end=1222
# @@protoc_insertion_point(module_scope)
