# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import chameleon.core.v1.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x11\x63hameleon.core.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"\x96\x02\n\x15ProcessMessageRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x14\n\x0crecipient_id\x18\x03 \x01(\t\x12\x0f\n\x07room_id\x18\x04 \x01(\t\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x17\n\nstyle_name\x18\x06 \x01(\tH\x00\x88\x01\x01\x12H\n\x08metadata\x18\x07 \x03(\x0b\x32\x36.chameleon.core.v1.ProcessMessageRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\r\n\x0b_style_name\"\xe2\x01\n\x16ProcessMessageResponse\x12\x14\n\x0c\x61\x64\x61pted_text\x18\x01 \x01(\t\x12\x13\n\x0bwas_adapted\x18\x02 \x01(\x08\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x12\n\nmodel_used\x18\x04 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x05 \x01(\x03\x12\x15\n\rrules_applied\x18\x06 \x03(\t\x12\x42\n\x13\x61\x64\x61ptation_metadata\x18\x07 \x01(\x0b\x32%.chameleon.core.v1.AdaptationMetadata\"\x8a\x01\n\x12\x41\x64\x61ptationMetadata\x12\x12\n\nfrom_cache\x18\x01 \x01(\x08\x12\x15\n\rfallback_used\x18\x02 \x01(\x08\x12\x17\n\x0f\x66\x61llback_reason\x18\x03 \x01(\t\x12\x15\n\rtokens_prompt\x18\x04 \x01(\x05\x12\x19\n\x11tokens_completion\x18\x05 \x01(\x05\x32\xc4\x01\n\x13OrchestratorService\x12\x65\n\x0eProcessMessage\x12(.chameleon.core.v1.ProcessMessageRequest\x1a).chameleon.core.v1.ProcessMessageResponse\x12\x46\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1f.chameleon.core.v1.HealthStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSMESSAGEREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_PROCESSMESSAGEREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PROCESSMESSAGEREQUEST']._serialized_start=85
  _globals['_PROCESSMESSAGEREQUEST']._serialized_end=363
  _globals['_PROCESSMESSAGEREQUEST_METADATAENTRY']._serialized_start=301
  _globals['_PROCESSMESSAGEREQUEST_METADATAENTRY']._serialized_end=348
  _globals['_PROCESSMESSAGERESPONSE']._serialized_start=366
  _globals['_PROCESSMESSAGERESPONSE']._serialized_end=592
  _globals['_ADAPTATIONMETADATA']._serialized_start=595
  _globals['_ADAPTATIONMETADATA']._serialized_end=733
  _globals['_ORCHESTRATORSERVICE']._serialized_start=736
  _globals['_ORCHESTRATORSERVICE']._serialized_end=932
# @@protoc_insertion_point(module_scope)
