# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chameleon.core.v1.common_pb2 as common__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import chameleon.core.v1.retriever_pb2 as retriever__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in retriever_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RetrieverServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProfile = channel.unary_unary(
                '/chameleon.core.v1.RetrieverService/GetProfile',
                request_serializer=retriever__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=retriever__pb2.UserProfile.FromString,
                _registered_method=True)
        self.GetRules = channel.unary_unary(
                '/chameleon.core.v1.RetrieverService/GetRules',
                request_serializer=retriever__pb2.GetRulesRequest.SerializeToString,
                response_deserializer=retriever__pb2.GetRulesResponse.FromString,
                _registered_method=True)
        self.GetStyleExamples = channel.unary_unary(
                '/chameleon.core.v1.RetrieverService/GetStyleExamples',
                request_serializer=retriever__pb2.GetStyleExamplesRequest.SerializeToString,
                response_deserializer=retriever__pb2.GetStyleExamplesResponse.FromString,
                _registered_method=True)
        self.SearchRules = channel.unary_unary(
                '/chameleon.core.v1.RetrieverService/SearchRules',
                request_serializer=retriever__pb2.SearchRulesRequest.SerializeToString,
                response_deserializer=retriever__pb2.SearchRulesResponse.FromString,
                _registered_method=True)
        self.SearchCulture = channel.unary_unary(
                '/chameleon.core.v1.RetrieverService/SearchCulture',
                request_serializer=retriever__pb2.SearchCultureRequest.SerializeToString,
                response_deserializer=retriever__pb2.SearchCultureResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/chameleon.core.v1.RetrieverService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.HealthStatus.FromString,
                _registered_method=True)


class RetrieverServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStyleExamples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchCulture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrieverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=retriever__pb2.GetProfileRequest.FromString,
                    response_serializer=retriever__pb2.UserProfile.SerializeToString,
            ),
            'GetRules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRules,
                    request_deserializer=retriever__pb2.GetRulesRequest.FromString,
                    response_serializer=retriever__pb2.GetRulesResponse.SerializeToString,
            ),
            'GetStyleExamples': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStyleExamples,
                    request_deserializer=retriever__pb2.GetStyleExamplesRequest.FromString,
                    response_serializer=retriever__pb2.GetStyleExamplesResponse.SerializeToString,
            ),
            'SearchRules': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchRules,
                    request_deserializer=retriever__pb2.SearchRulesRequest.FromString,
                    response_serializer=retriever__pb2.SearchRulesResponse.SerializeToString,
            ),
            'SearchCulture': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCulture,
                    request_deserializer=retriever__pb2.SearchCultureRequest.FromString,
                    response_serializer=retriever__pb2.SearchCultureResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=common__pb2.HealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chameleon.core.v1.RetrieverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chameleon.core.v1.RetrieverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RetrieverService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chameleon.core.v1.RetrieverService/GetProfile',
            retriever__pb2.GetProfileRequest.SerializeToString,
            retriever__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chameleon.core.v1.RetrieverService/GetRules',
            retriever__pb2.GetRulesRequest.SerializeToString,
            retriever__pb2.GetRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStyleExamples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chameleon.core.v1.RetrieverService/GetStyleExamples',
            retriever__pb2.GetStyleExamplesRequest.SerializeToString,
            retriever__pb2.GetStyleExamplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chameleon.core.v1.RetrieverService/SearchRules',
            retriever__pb2.SearchRulesRequest.SerializeToString,
            retriever__pb2.SearchRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchCulture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chameleon.core.v1.RetrieverService/SearchCulture',
            retriever__pb2.SearchCultureRequest.SerializeToString,
            retriever__pb2.SearchCultureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chameleon.core.v1.RetrieverService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            common__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
